[[constraint]]
  name = "github.com/docker/go-connections"
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"

[[constraint]]
  name = "github.com/docker/go-plugins-helpers"
  revision = "a9ef19c479cb60e751efa55f7f2b265776af1abf"

